# Generated by Django 5.1 on 2025-05-08 11:42

import django.db.models.deletion
import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_url_local', models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_wrapper)),
                ('news_shared_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SearchWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Search Word')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Word',
                'verbose_name_plural': 'Search Words',
            },
        ),
        migrations.CreateModel(
            name='ChangedNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('news_shared_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changednewsarticles', to='scraper.newsarticle')),
            ],
            options={
                'verbose_name': 'Changed News Article',
                'verbose_name_plural': 'Changed News Articles',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_link', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Site Link')),
                ('rss_link', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RSS Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='scraper.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsarticles', to='scraper.source', verbose_name='Source'),
        ),
    ]
