# Generated by Django 5.1 on 2025-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='full_site_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Site Name'),
        ),
    ]
