# Generated by Django 5.1 on 2025-05-12 10:39

import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_source_full_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='changednewsarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url_local',
            field=models.ImageField(blank=True, default='default/no-image.jpg', null=True, upload_to=utils.photo_save.logo_dir_wrapper),
        ),
    ]
