# Generated by Django 5.1 on 2025-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_changednewsarticle_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='site_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='source',
            name='full_site_name',
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Site Name'),
        ),
    ]
