# Generated by Django 5.1 on 2025-05-12 13:48

import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_rename_site_link_source_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url_local',
            field=models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_wrapper),
        ),
    ]
