# Generated by Django 5.1 on 2025-05-15 08:40

import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_newsarticle_image_url_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='changednewsarticle',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changednewsarticle',
            name='image_url_local',
            field=models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_wrapper),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
