# Generated by Django 5.1 on 2025-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_changednewsarticle_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
