# Generated by Django 5.1 on 2025-05-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_newsarticle_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_checked',
        ),
    ]
