# Generated by Django 5.1 on 2025-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_remove_newsarticle_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_downloading_image',
            field=models.BooleanField(default=False),
        ),
    ]
