# Generated by Django 5.1 on 2025-05-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_newsarticle_is_downloading_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_downloading_image',
        ),
    ]
