# Generated by Django 5.1 on 2025-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_remove_newsarticle_is_downloading_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changednewsarticle',
            name='image_url_local',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
