# Generated by Django 5.1 on 2025-05-30 14:11

import django.core.files.storage
import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_changednewsarticle_image_url_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url_local',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=utils.photo_save.logo_dir_wrapper),
        ),
    ]
