# Generated by Django 5.1 on 2025-06-30 10:47

import django.db.models.deletion
import scraper.models
import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_newsarticle_image_url_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changednewsarticle',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='changednewsarticle',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='changednewsarticle',
            name='image_url_local',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_url_local',
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('local_image_url', models.ImageField(blank=True, null=True, storage=scraper.models.UniqueImageStorage(), upload_to=utils.photo_save.logo_dir_wrapper)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_newsarticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.changednewsarticle')),
                ('newsarticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.newsarticle')),
            ],
            options={
                'verbose_name': 'News Image',
                'verbose_name_plural': 'News Images',
            },
        ),
    ]
