# Generated by Django 5.1 on 2025-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_remove_changednewsarticle_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='base64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
