# Generated by Django 5.1 on 2025-08-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_newsimage_base64_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='local_image_url',
        ),
    ]
