# Generated by Django 5.1 on 2025-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_remove_newsimage_local_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
