# Generated by Django 5.1 on 2025-10-06 12:54

import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_alter_newsimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='local_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=scraper.models.news_image_path),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
