# Generated by Django 5.1 on 2025-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_newsimage_local_image_url_alter_newsimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
