# Generated by Django 5.1 on 2025-10-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type'),
        ),
    ]
