# Generated by Django 5.1 on 2025-10-14 11:34

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', multiselectfield.db.fields.MultiSelectField(choices=[('title', 'Title'), ('description', 'Description'), ('content', 'Content'), ('news_shared_date', 'News Shared Date')], max_length=42, null=True, verbose_name='Fields to Exclude')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludes', to='scraper.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Exclude',
                'verbose_name_plural': 'Excludes',
            },
        ),
    ]
