# Generated by Django 5.1 on 2025-10-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='newsarticle',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='task',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
