# Generated by Django 5.1 on 2025-10-21 14:07

import scraper.models
#from utils.upload_remote_scp import RemoteStorage

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0024_remove_problem_category_remove_task_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='local_image_url',
            field=models.ImageField(
    		blank=True,
    		null=True,
 #   		storage=RemoteStorage(),
    		upload_to=scraper.models.news_image_path,
	    ),
        ),
    ]
