# Generated by Django 5.1 on 2025-10-24 12:02

import scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0026_alter_newsimage_local_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='local_image_url',
            field=models.ImageField(blank=True, max_length=2048, null=True, upload_to=scraper.models.news_image_path),
        ),
    ]
