# Generated by Django 5.1 on 2025-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0028_source_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changednewsarticle',
            name='title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
