# Generated by Django 5.1 on 2026-03-17 08:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_alter_changednewsarticle_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclude',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('title', 'Title'), ('description', 'Description'), ('content', 'Content'), ('news_shared_date', 'News Shared Date'), ('image', 'Image')], max_length=150, null=True, verbose_name='Fields to Exclude'),
        ),
    ]
