# Generated by Django 5.1 on 2026-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0030_alter_exclude_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exclude',
            constraint=models.UniqueConstraint(fields=('source',), name='unique_exclude_per_source'),
        ),
    ]
