# Generated by Django 5.1 on 2026-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
