# Generated by Django 5.1 on 2026-09-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_problem_problem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(choices=[('css_selector', 'CSS Selector'), ('meta', 'Meta Tag')], default='css_selector', max_length=30)),
                ('rule_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rules', to='management.problem')),
            ],
            options={
                'verbose_name': 'Source Extraction Rule',
                'verbose_name_plural': 'Source Extraction Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
