# Generated by Django 5.1 on 2026-09-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_sourcerule'),
        ('scraper', '0031_exclude_unique_exclude_per_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerule',
            name='resolution_type',
            field=models.CharField(choices=[('css_selector', 'CSS Selector'), ('meta', 'Meta Tag'), ('json_ld', 'JSON-LD'), ('api_json', 'API JSON'), ('url_regex', 'URL Regex')], default='css_selector', max_length=30),
        ),
        migrations.CreateModel(
            name='AutoHealerFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=15)),
                ('resolution_type', models.CharField(choices=[('css_selector', 'CSS Selector'), ('meta', 'Meta Tag'), ('json_ld', 'JSON-LD'), ('api_json', 'API JSON'), ('url_regex', 'URL Regex')], max_length=30)),
                ('rule_content', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence_urls', models.TextField(blank=True, help_text='JSON list of sample URLs that generated this finding.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_healer_findings', to='scraper.source')),
            ],
            options={
                'verbose_name': 'Auto Healer Finding',
                'verbose_name_plural': 'Auto Healer Findings',
                'constraints': [models.UniqueConstraint(fields=('source', 'category', 'resolution_type', 'rule_content'), name='unique_finding_candidate')],
            },
        ),
    ]
