"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m$dp&!6po+33nv8v3_l89a6&xq^(h@7mo%@4yq77(b9-m$%st%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #local
    
    "scraper.apps.ScraperConfig",
    'tasks',
    'management',
    'user',
    # 3rd party
    
    'django_celery_beat',
    #'django_celery_results',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


CORS_ALLOW_ALL_ORIGINS =True
CORS_ALLOW_HEADERS = [
    "content-type",
    "x-auth-token",
    "x-user-id",
    "x-expire-date",
]

CACHES = {

    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },

    "redis": {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": "redis://localhost:6379/2",
    "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"}
    }

}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DATABASE_NAME', 'scrape_db3'),
        'USER': os.getenv('DATABASE_USERNAME', 'scrape_user'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'YaKRp92XMsoeCm4A'),
        'HOST': os.getenv('DATABASE_HOST', '192.168.0.203'),
        'PORT': os.getenv('DATABASE_PORT', 5432),
    }
}


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/


LANGUAGE_CODE = 'az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_TIMEZONE = "Asia/Baku"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


CELERY_IMPORTS = [
    'management.tasks',
]


CELERY_BEAT_SCHEDULE = {
    
    # gündə 4 dəfə
#     "send-email-morning": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=8, minute=0),
#         "options": {  
#             "queue": "email_queue"  
#         } 
#     },
#     "send-email-noon": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=12, minute=0),
#         "options": {  
#             "queue": "email_queue"  
#         } 
#     },
#     "send-email-evening": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=16, minute=0),
#         "options": {  
#             "queue": "email_queue"  
#         } 
#     },
#     "send-email-night": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=21, minute=0),
#         "options": {  
#             "queue": "email_queue"  
#         } 
#     },
#     "celery-build-temp-mail-data": {
#         "task": "scraper.tasks.celery_build_temp_mail_data",
#         "schedule": crontab(minute="*/2"),
#         "options": {  
#             "queue": "email_queue"  
#         }
#     },
#     
# 
#     "celery-send-keywords-telegram-specific-hours": {
#         "task": "scraper.tasks.celery_send_keywords_telegram",
#         "schedule": crontab(minute=0, hour="*/4"),
#     },
# 
#     "celery-build-temp-telegram-data": {
#         "task": "scraper.tasks.celery_build_temp_telegram_data",
#         "schedule": crontab(minute="*/3"),
#     },
#     
# 
# 
#     'fetch-izru-every-3-minutes': {
#          'task': 'scraper.tasks.fetch_news_links_izru',
#         'schedule': crontab(minute='*/3'),
#     },
#    


    # 'trigger_image_auto_healing-every-25-minutes': {
    #     'task': 'management.auto_healer.auto_healer_tasks.trigger_image_auto_healing',
    #     'schedule': crontab(minute='*/25'),
    # },

    # 'trigger_title_auto_healing-every-25-minutes': {
    #     'task': 'management.auto_healer.auto_healer_tasks.trigger_title_auto_healing',
    #     'schedule': crontab(minute='*/25'),
    # },

    # 'trigger_content_auto_healing-every-25-minutes': {
    #     'task': 'management.auto_healer.auto_healer_tasks.trigger_content_auto_healing',
    #     'schedule': crontab(minute='*/25'),
    # },

    # 'trigger_description_auto_healing-every-25-minutes': {
    #     'task': 'management.auto_healer.auto_healer_tasks.trigger_description_auto_healing',
    #     'schedule': crontab(minute='*/25'),
    # },
    # 'trigger_date_auto_healing-every-25-minutes': {
    #     'task': 'management.auto_healer.auto_healer_tasks.trigger_date_auto_healing',
    #     'schedule': crontab(minute='*/25'),
    # },

    'trigger-all-auto-healing-every-30-minutes': {
        'task': 'management.tasks.trigger_all_auto_healing',
        'schedule': crontab(minute='*/30'),
    },




    'fetch-lentaru-every-4-minutes': {
        'task': 'scraper.tasks.fetch_news_links_lentaru',
        'schedule': crontab(minute='*/4'),
    },
    
    # 'fetch-oxu-every-four-minutes': {
    # 'task': 'scraper.tasks.fetch_news_links_oxu',
    # 'schedule': crontab('*/6'), 
    #     },

    'fetch-apa-every-5-minutes': {
        'task': 'scraper.tasks.fetch_news_links_apa',
        'schedule': crontab(minute='*/5'),
    },
    
    'fetch-cumhuriyet-every-6-minutes': {
        'task': 'scraper.tasks.fetch_news_links_cumhuriyet',
        'schedule': crontab(minute='*/6'), 
        },
    
    # 'fetch-report-every-six-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_report',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-unian-every-7-minutes': {
        'task': 'scraper.tasks.fetch_news_links_unian_net',
        'schedule': crontab(minute='*/7'), 
        },

    # 'fetch-tass-ru-every-six-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_tass_ru',
    #     'schedule': crontab(minute='*'), 
    #     },

    # 'fetch-beltaby-every-8-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_belta_by',
    #     'schedule': crontab(minute='*/8'),
    # },

    # 'fetch-azertag-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_azertag',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-editor-every-21-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_editor',
    #     'schedule': crontab(minute='*/21'),
    # },

    'fetch-azxeber-every-8-minutes': {
        'task': 'scraper.tasks.fetch_news_links_azxeber',
        'schedule': crontab(minute='*/8'),
    },

    'fetch-lent-every-9-minutes': {
        'task': 'scraper.tasks.fetch_news_links_lent',
        'schedule': crontab(minute='*/9'),
    },

    'fetch-orda-kz-every-10-minutes': {
        'task': 'scraper.tasks.fetch_news_links_orda_kz',
        'schedule': crontab(minute='*/10'),
    },

    'fetch-metbuat-every-11-minute': {
        'task': 'scraper.tasks.fetch_news_links_metbuat',
        'schedule': crontab(minute='*/11'),
    },

    'fetch-rbcua-every-12-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rbc_ua',
        'schedule': crontab(minute='*/12'),
    },

    # 'fetch-nv-ua-every-ten-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_nv_ua',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-bakuws-every-seventeen-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_bakuws',
    #     'schedule': crontab(minute='*'),
    # },    
    
    # 'fetch-xezerxeber-every-eleven-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_xezerxeber',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-trend-every-13-minutes': {
    'task': 'scraper.tasks.fetch_news_links_trend',
    'schedule': crontab(minute='*/13'), 
    },
    
    'fetch-milli-every-14-minutes': {
    'task': 'scraper.tasks.fetch_news_links_milli',
    'schedule': crontab(minute='*/14'), 
    },
    
    # #-----------FOREIGN NEWS----------------
    
    # 'fetch-bbc-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_bbc',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-milliyet-every-14-minutes': {
        'task': 'scraper.tasks.fetch_news_links_milliyet',
        'schedule': crontab(minute='*/14'), 
    },

    # 'fetch-kaztag-kz-every-thirteen-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_kaztag_kz',
    #     'schedule': crontab(minute='*'), 
    # },

    'fetch-armeniatoday-every-15-minutes': {
        'task': 'scraper.tasks.fetch_news_links_armeniatoday',
        'schedule': crontab(minute='*/15'),
    },
    
    # 'fetch-sputnikarm-every-twentyone-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_sputnikarm',
    #     'schedule': crontab(minute='*/21'),
    # },
    
    # 'fetch-kpru-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_kpru',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-civilge-every-twentyfive-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_civilge',
    #     'schedule': crontab(minute='*/25'),
    # },
    
    # 'fetch-trthaber-every-twentyeight-minutes': {
    # 'task': 'scraper.tasks.fetch_news_links_trthaber',
    # 'schedule': crontab(minute='*/28'), 
    #     },

    # 'fetch-internethaber-every-twentynine-minutes': {
    # 'task': 'scraper.tasks.fetch_news_links_internethaber',
    # 'schedule': crontab(minute='*/29'), 
    #     },

    'fetch-infoxru-every-16-minutes': {
        'task': 'scraper.tasks.fetch_news_links_infoxru',
        'schedule': crontab(minute='*/16'), 
    },

    # 'download-missing-images-every-minute': {
    #     'task': 'scraper.tasks.download_missing_news_images',
    #     'schedule': crontab(minute='*'),  
    # },
    
    # 'fetch-az-sputniknews-ru-every-fiveteen-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_az_sputniknews_ru',
    #     'schedule': crontab(minute='*'), 
    # },

    # 'fetch-mirror-every-thirty-one-minutes': {
    # 'task': 'scraper.tasks.fetch_news_links_mirror',
    # 'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-sozcu-every-17-minutes': {
        'task': 'scraper.tasks.fetch_news_links_sozcu',
        'schedule': crontab(minute='*/17'), 
    },

   'fetch-nur-kz-every-18-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nur_kz',
        'schedule': crontab(minute='*/18'), 
    }, 
    
    'fetch-samanyolu-every-19-minutes': {
        'task': 'scraper.tasks.fetch_news_links_samanyoluhaber',
        'schedule': crontab(minute='*/19'), 
    },
    
    # 'fetch-haberturk-every-thirty-five-minutes': {
    # 'task': 'scraper.tasks.fetch_news_links_haberturk',
    # 'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-sabah-every-20-minutes': {
        'task': 'scraper.tasks.fetch_news_links_sabah',
        'schedule': crontab(minute='*/20'), 
    },
    
    'fetch-gercekgundem-every-21-minutes': {
        'task': 'scraper.tasks.fetch_news_links_gercekgundem',
        'schedule': crontab(minute='*/21'),
    },

    'fetch-birgun-every-22-minutes': {
        'task': 'scraper.tasks.fetch_news_links_birgun',
        'schedule': crontab(minute='*/22'), 
    },
    
    'fetch-bianet-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_bianet',
        'schedule': crontab(minute='*/23'), 
    },
    
    'fetch-voaturkce-every-24-minutes': {
        'task': 'scraper.tasks.fetch_news_links_voaturkce',
        'schedule': crontab(minute='*/24'), 
    },
    
    'fetch-anlatilaninotesi-every-25-minutes': {
        'task': 'scraper.tasks.fetch_news_links_anlatilaninotesi',
        'schedule': crontab(minute='*/25'), 
    },
    
    # 'fetch-dwcom-every-twenty-four-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_dwcom',
    #     'schedule': crontab(minute='*'), 
    #     },

    'fetch-uz-sputniknews-ru-every-26-minutes': {
        'task': 'scraper.tasks.fetch_news_links_uz_sputniknews_ru',
        'schedule': crontab(minute='*/26'), 
    },
    
    'fetch-ulusal-every-27-minutes': {
        'task': 'scraper.tasks.fetch_news_links_ulusal',
        'schedule': crontab(minute='*/27'), 
    },
    
    'fetch-gazeta-uz-every-28-minutes': {
        'task': 'scraper.tasks.fetch_news_links_gazeta_uz',
        'schedule': crontab(minute='*/28'), 
    },

    'fetch-haberler-every-29-minutes': {
        'task': 'scraper.tasks.fetch_news_links_haberler',
        'schedule': crontab(minute='*/29'),
    },

    'fetch-am-sputniknews-ru-every-30-minutes': {
        'task': 'scraper.tasks.fetch_news_links_am_sputniknews_ru',
        'schedule': crontab(minute='*/30'), 
    },
    
    # 'fetch-rasthaber-every-twenty-seven-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_rasthaber',
    #     'schedule': crontab(minute='*'), 
    #     },

    # 'fetch-sputnik-georgia-ru-every-twenty-seven-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_sputnik_georgia_ru',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-yeniakit-every-31-minutes': {
        'task': 'scraper.tasks.fetch_news_links_yeniakit',
        'schedule': crontab(minute='*/31'), 
    },
    
    'fetch-yenisafak-every-32-minutes': {
        'task': 'scraper.tasks.fetch_news_links_yenisafak',
        'schedule': crontab(minute='*/32'), 
    },
    
    # 'fetch-agos-every-thirty-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_agos',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-hdp-every-day-once': {
    #     'task': 'scraper.tasks.fetch_news_links_hdp',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-aa-every-33-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aa',
        'schedule': crontab(minute='*/33'),
        },
    
    'fetch-kronos38-every-34-minutes': {
        'task': 'scraper.tasks.fetch_news_links_kronos38',
        'schedule': crontab(minute='*/34'),
        },

    'fetch-centralasia-media-every-35-minutes': {
        'task': 'scraper.tasks.fetch_news_links_centralasia_media',
        'schedule': crontab(minute='*/35'),
        },

    'fetch-newsgeorgia-ge-every-36-minutes': {
        'task': 'scraper.tasks.fetch_news_links_newsgeorgia_ge',
        'schedule': crontab(minute='*/36'),
        },
    
    'fetch-mtavari-tv-every-37-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mtavari_tv',
        'schedule': crontab(minute='*/37'),
        },
    
    'fetch-formulanews-ge-every-38-minutes': {
        'task': 'scraper.tasks.fetch_news_links_formulanews_ge',
        'schedule': crontab(minute='*/38'),
        },
    
    'fetch-arm-sputniknews-ru-every-39-minutes': {
        'task': 'scraper.tasks.fetch_news_links_arm_sputniknews_ru',
        'schedule': crontab(minute='*/39'), 
        },
    
    # 'fetch-yerevan-today-every-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_yerevan_today',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-newsarmenia-am-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_newsarmenia_am',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-aravot-am-thirty-two-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aravot_am',
        'schedule': crontab(minute='*/32'), 
        },
    
    'fetch-infoport-am-40-minutes': {
        'task': 'scraper.tasks.fetch_news_links_infoport_am',
        'schedule': crontab(minute='*/40'), 
        },
    
    # 'fetch-armenpress-am-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_armenpress_am',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-arminfo-info-25-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_arminfo_info',
    #     'schedule': crontab(minute='*/25'), 
    #     },
    
    'fetch-armenianweekly-com-41-minutes': {
        'task': 'scraper.tasks.fetch_news_links_armenianweekly_com',
        'schedule': crontab(minute='*/41'), 
        },
    
    # 'fetch-irna-ir-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_irna_ir',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-alef-ir-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_alef_ir',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    # 'fetch-etemadonline-com-19-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_etemadonline_com',
    #     'schedule': crontab(minute='*/19'), 
    # },
    
    # 'fetch-esnafnews-com-24-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_esnafnews_com',
    #     'schedule': crontab(minute='*/24'), 
    # },
    
    # 'fetch-donya-e-eqtesad-com-13-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_donya_e_eqtesad_com',
    #     'schedule': crontab(minute='*/13'), 
    #     },
    
    # 'fetch-entekhab-ir-6-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_entekhab_ir',
    #     'schedule': crontab(minute='*/6'), 
    #     },
    
    # 'fetch-irdiplomacy-ir-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_irdiplomacy_ir',
    #     'schedule': crontab(minute='*/120'), 
    # },
    
    'fetch-kayhan-london-42-minutes': {
        'task': 'scraper.tasks.fetch_news_links_kayhan_london',
        'schedule': crontab(minute='*/42'),
        },
    
    'fetch-sedayemardom-net-43-minutes': {
        'task': 'scraper.tasks.fetch_news_links_sedayemardom_net',
        'schedule': crontab(minute='*/43'), 
        },
    
    'fetch-zeitoons-com-44-minutes': {
        'task': 'scraper.tasks.fetch_news_links_zeitoons_com',
        'schedule': crontab(minute='*/44'), 
        },
    
    # 'fetch-fararu-com-4-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_fararu_com',
    #     'schedule': crontab(minute='*/4'),
    # },
    
    # 'fetch-ilna-ir-11-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_ilna_ir',
    #     'schedule': crontab(minute='*/11'), 
    # },
    
    # 'fetch-hamshahrionline-ir-20-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_hamshahrionline_ir',
    #     'schedule': crontab(minute='*/20'), 
    # },
    
    # 'fetch-khabaronline-ir-27-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_khabaronline_ir',
    #     'schedule': crontab(minute='*/27'),
    # },
    
    'fetch-mehrnews-com-45-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mehrnews_com',
        'schedule': crontab(minute='*/45'), 
    },
    
    # 'fetch-mashreghnews-ir-14-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_mashreghnews_ir',
    #     'schedule': crontab(minute='*/14'), 
    # },
    
    # 'fetch-aftabnews-ir-10-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_aftabnews_ir',
    #     'schedule': crontab(minute='*/10'), 
    # },
                       
    # 'fetch-mojnews-com-25-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_mojnews_com',
    #     'schedule': crontab(minute='*/25'), 
    # },
    
    # 'fetch-atna-atu-ac-ir-com-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_atna_atu_ac_ir',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-melliun-org-46-minutes': {
        'task': 'scraper.tasks.fetch_news_links_melliun_org',
        'schedule': crontab(minute='*/46'), 
    },
    
    # 'fetch-isna-ir-7-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_isna_ir',
    #     'schedule': crontab(minute='*/7'),
    # },

    # 'fetch-tejaratnews-com-thirty-two-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_tejaratnews_com',
    #     'schedule': crontab(minute='*'), 
    #     },
    
    'fetch-npr-org-every-47-minutes': {
        'task': 'scraper.tasks.fetch_news_links_npr_org',
        'schedule': crontab(minute='*/47'),
    },

    'fetch-calmatters-org-every-48-minutes': {
        'task': 'scraper.tasks.fetch_news_links_calmatters_org',
        'schedule': crontab(minute='*/48'),
    },

    'fetch-foxnews-com-every-49-minutes': {
        'task': 'scraper.tasks.fetch_news_links_foxnews_com',
        'schedule': crontab(minute='*/49'),
    },

    'fetch-huffpost-com-every-50-minutes': {
        'task': 'scraper.tasks.fetch_news_links_huffpost_com',
        'schedule': crontab(minute='*/50'),
    },
    
    'fetch-kqed-org-every-51-minutes': {
        'task': 'scraper.tasks.fetch_news_links_kqed_org',
        'schedule': crontab(minute='*/51'),
    },
    
    'fetch-pbs-org-every-52-minutes': {
        'task': 'scraper.tasks.fetch_news_links_pbs_org',
        'schedule': crontab(minute='*/52'),
    },

    'fetch-nbcnews-com-every-53-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nbcnews_com',
        'schedule': crontab(minute='*/53'),
    },

    'fetch-news-sky-com-every-54-minutes': {
        'task': 'scraper.tasks.fetch_news_links_news_sky_com',
        'schedule': crontab(minute='*/54'),
    },

    'fetch-theguardian-com-every-55-minutes': {
        'task': 'scraper.tasks.fetch_news_links_theguardian_com',
        'schedule': crontab(minute='*/55'),
    },

    'fetch-theconversation-com-every-56-minutes': {
        'task': 'scraper.tasks.fetch_news_links_theconversation_com',
        'schedule': crontab(minute='*/56'),
    },
    
    # 'fetch-vox-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_vox_com',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-independent-co-uk-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_independent_co_uk',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-msnbc-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_msnbc_com',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-newsweek-com-every-15-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_newsweek_com',
    #     'schedule': crontab(minute='*/15'),
    # },
    
    # 'fetch-thehindu-com-every-31-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_thehindu_com',
    #     'schedule': crontab(minute='*/31'),
    # },

    # 'fetch-yahoo-com-every-45-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_yahoo_com',
    #     'schedule': crontab(minute='*/45'),
    # },

    # 'fetch-boston-com-every-40-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_boston_com',
    #     'schedule': crontab(minute='*/40'),
    # },
    
    # 'fetch-greatreporter-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_greatreporter_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-cbsnews-com-every-57-minutes': {
        'task': 'scraper.tasks.fetch_news_links_cbsnews_com',
        'schedule': crontab(minute='*/57'),
    },

    'fetch-ipsnews-net-every-58-minutes': {
        'task': 'scraper.tasks.fetch_news_links_ipsnews_net',
        'schedule': crontab(minute='*/58'),
    },

    'fetch-upi-com-every-59-minutes': {
        'task': 'scraper.tasks.fetch_news_links_upi_com',
        'schedule': crontab(minute='*/59'),
    },

    'fetch-sbs-com-au-every-3-minutes': {
        'task': 'scraper.tasks.fetch_news_links_sbs_com_au',
        'schedule': crontab(minute='*/3'),
    },
    
    'fetch-latimes-com-every-4-minutes': {
        'task': 'scraper.tasks.fetch_news_links_latimes_com',
        'schedule': crontab(minute='*/4'),
    },
    
    # 'fetch-thedispatch-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_thedispatch_com',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-globalnews-ca-every-5-minutes': {
        'task': 'scraper.tasks.fetch_news_links_globalnews_ca',
        'schedule': crontab(minute='*/5'),
    },

    'fetch-chp-org-tr-every-6-minutes': {
        'task': 'scraper.tasks.fetch_news_links_chp_org_tr',
        'schedule': crontab(minute='*/6'),
    },

    'fetch-nydailynews-com-every-7-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nydailynews_com',
        'schedule': crontab(minute='*/7'),
    },

    'fetch-iyiparti-org-tr-every-8-minutes': {
        'task': 'scraper.tasks.fetch_news_links_iyiparti_org_tr',
        'schedule': crontab(minute='*/8'),
    },
    
    # 'fetch-tr-euronews-com-tr-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_tr_euronews_com',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-news24-ge-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_24news_ge',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-interpressnews-ge-every-9-minutes': {
        'task': 'scraper.tasks.fetch_news_links_interpressnews_ge',
        'schedule': crontab(minute='*/9'),
    },

    'fetch-aysor-am-every-10-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aysor_am',
        'schedule': crontab(minute='*/10'),
    },

    # 'fetch-tert-am-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_tert_am',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-qomnews-ir-every-73-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_qomnews_ir',
    #     'schedule': crontab(minute='*/73'),
    # },

    # 'fetch-iribnews-ir-every-5-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_iribnews_ir',
    #     'schedule': crontab(minute='*/5'),
    # },
    
    # 'fetch-news_gooya-ir-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_news_gooya_ir',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-tasnimnews-com-every-16-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_tasnimnews_com',
    #     'schedule': crontab(minute='*/16'),
    # },

    'fetch-tabnak-ir-every-16-minutes': {
        'task': 'scraper.tasks.fetch_news_links_tabnak_ir',
        'schedule': crontab(minute='*/16'),
    },

    # 'fetch-qafqazagency-ir-every-8-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_qafqazagency_ir',
    #     'schedule': crontab(minute='*/8'),
    # },

    'fetch-gunaz-tv-every-20-minutes': {
        'task': 'scraper.tasks.fetch_news_links_gunaz_tv',
        'schedule': crontab(minute='*/20'),
    },

    'fetch-gadtb-com-every-11-minutes': {
        'task': 'scraper.tasks.fetch_news_links_gadtb_com',
        'schedule': crontab(minute='*/11'),
    },

    # 'fetch-hoosk-ir-every-300-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_hoosk_ir',
    #     'schedule': crontab(minute='*/300'),
    # },

    # 'fetch-tehranprelacy-com-every-250-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_tehranprelacy_com',
    #     'schedule': crontab(minute='*/250'),
    # },
    
    # 'fetch-rokna-net-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_rokna_net',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-jamejamonline-ir-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_jamejamonline_ir',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-fardanews-com-every-30-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_fardanews_com',
    #     'schedule': crontab(minute='*/30'),
    # },

    # 'fetch-bbc-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_bbc_com',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-slate-com-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_slate_com',
        'schedule': crontab(minute='*/23'),
    },

    'fetch-nypost-com-every-37-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nypost_com',
        'schedule': crontab(minute='*/37'),
    },

    'fetch-chicagotribune-com-every-32-minutes': {
        'task': 'scraper.tasks.fetch_news_links_chicagotribune_com',
        'schedule': crontab(minute='*/32'),
    },
    
    # 'fetch-radiozamaneh-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_radiozamaneh_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-bbcpersian-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_bbcpersian_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-farsnews-ir-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_farsnews_ir',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-rfi-fr-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_rfi_fr_fa',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-iranwire-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_iranwire_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-avatoday-net-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_avatoday_net',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-balatarin-com-every-50-minutes': {
        'task': 'scraper.tasks.fetch_news_links_balatarin_com',
        'schedule': crontab(minute='*/50'),
    },
    
    # 'fetch-english-alarabiya-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_english_alarabiya_net',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-iraintl-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_iranintl_com',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-mirrorspectator-com-every-24-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_mirrorspectator_com',
    #     'schedule': crontab(minute='*/24'),
    # },
    
    # 'fetch-bloomberght-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_bloomberght_com',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-nordicmonitor-com-every-12-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nordicmonitor_com',
        'schedule': crontab(minute='*/12'),
    },

    'fetch-norharatch-com-every-13-minutes': {
        'task': 'scraper.tasks.fetch_news_links_norharatch_com',
        'schedule': crontab(minute='*/13'),
    },

    'fetch-sondakika-com-every-16-minutes': {
        'task': 'scraper.tasks.fetch_news_links_sondakika_com',
        'schedule': crontab(minute='*/16'),
    },
    
    # 'fetch-tvpirveli-ge-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_tvpirveli_ge',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-rustavi2-ge-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_rustavi2_ge',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-onetv-ge-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_onetv_ge',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-mamul-am-every-14-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mamul_am',
        'schedule': crontab(minute='*/14'),
    },

    # 'fetch-radiofarda-com-every-17-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_radiofarda_com',
    #     'schedule': crontab(minute='*/17'),
    # },

    # 'fetch-news-am-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_news_am',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-onein-am-every-10-minutes': {
        'task': 'scraper.tasks.fetch_news_links_onein_am',
        'schedule': crontab(minute='*/10'),
    },

    'fetch-uk-news-yahoo-com-every-35-minutes': {
        'task': 'scraper.tasks.fetch_news_links_uk_yahoo_com',
        'schedule': crontab(minute='*/35'),
    },
    
    # 'fetch-telegraph-co-uk-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_telegraph_co_uk',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-thesun-co-uk-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_thesun_co_uk',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-mirror-co-uk-every-22-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mirror_co_uk',
        'schedule': crontab(minute='*/22'),
    },

    'fetch-metro-co-uk-every-38-minutes': {
        'task': 'scraper.tasks.fetch_news_links_metro_co_uk',
        'schedule': crontab(minute='*/38'),
    },
    
    'fetch-dailyrecord-co-uk-every-26-minutes': {
        'task': 'scraper.tasks.fetch_news_links_dailyrecord_co_uk',
        'schedule': crontab(minute='*/26'),
    },

    'fetch-express-co-uk-every-29-minutes': {
        'task': 'scraper.tasks.fetch_news_links_express_co_uk',
        'schedule': crontab(minute='*/29'),
    },

    'fetch-manchestereveningnews-co-uk-every-26-minutes': {
        'task': 'scraper.tasks.fetch_news_links_manchestereveningnews_co_uk',
        'schedule': crontab(minute='*/26'),
    },
    
    # 'fetch-standart-co-uk-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_standard_co_uk',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-walesonline-co-uk-every-24-minutes': {
        'task': 'scraper.tasks.fetch_news_links_walesonline_co_uk',
        'schedule': crontab(minute='*/24'),
    },
    
    # 'fetch-thescottishsun-co-uk-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_thescottishsun_co_uk',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-heraldscotland-com-every-22-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_heraldscotland_com',
    #     'schedule': crontab(minute='*/22'),
    # },
    
    'fetch-expressandstar-com-every-32-minutes': {
        'task': 'scraper.tasks.fetch_news_links_expressandstar_com',
        'schedule': crontab(minute='*/32'),
    },
    
    'fetch-news-stv-tv-every-29-minutes': {
        'task': 'scraper.tasks.fetch_news_links_news_stv_tv',
        'schedule': crontab(minute='*/29'),
    },
    
    'fetch-armenews-com-every-15-minute': {
        'task': 'scraper.tasks.fetch_news_links_armenews_com',
        'schedule': crontab(minute='*/15'),
    },
    
    'fetch-caucasefrance-com-every-43-minute': {
        'task': 'scraper.tasks.fetch_news_links_caucasefrance_com',
        'schedule': crontab(minute='*/43'),
    },
    
    # 'fetch-miasinnews-by-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_miasinnews_by',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-timesofindia-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_timesofindia_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-ndtv-com-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_ndtv_com',
        'schedule': crontab(minute='*/23'),
    },

    # 'fetch-walla-co-il-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_walla_co_il',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-ynet-co-il-every-9-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_ynet_co_il',
    #     'schedule': crontab(minute='*/9'),
    # },

    'fetch-mako-co-il-every-41-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mako_co_il',
        'schedule': crontab(minute='*/41'),
    },

    'fetch-13tv-co-il-every-17-minutes': {
        'task': 'scraper.tasks.fetch_news_links_13tv_co_il',
        'schedule': crontab(minute='*/17'),
    },

    'fetch-israelhayom-com-every-15-minutes': {
        'task': 'scraper.tasks.fetch_news_links_israelhayom_com',
        'schedule': crontab(minute='*/15'),
    },
    
    # 'fetch-jpost-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_jpost_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    'fetch-newsru-co-il-every-30-minutes': {
        'task': 'scraper.tasks.fetch_news_links_newsru_co_il',
        'schedule': crontab(minute='*/30'),
    },

    'fetch-cursorinfo-co-il-every-13-minutes': {
        'task': 'scraper.tasks.fetch_news_links_cursorinfo_co_il',
        'schedule': crontab(minute='*/13'),
    },

    'fetch-9-tv-co-il-every-21-minutes': {
        'task': 'scraper.tasks.fetch_news_links_9tv_co_il',
        'schedule': crontab(minute='*/21'),
    },
    
    'fetch-israelinfo-co-il-every-53-minutes': {
        'task': 'scraper.tasks.fetch_news_links_israelinfo_co_il',
        'schedule': crontab(minute='*/53'),
    },
    
    'fetch-mignews-com-every-44-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mignews_com',
        'schedule': crontab(minute='*/44'),
    },
    
    'fetch-alaraby-co-uk-every-18-minutes': {
        'task': 'scraper.tasks.fetch_news_links_alaraby_co_uk',
        'schedule': crontab(minute='*/18'),
    },
    
    # 'fetch-alkhaleej-ae-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_alkhaleej_ae',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-aljazeera-net-every-30-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aljazeera_net',
        'schedule': crontab(minute='*/30'),
    },

    'fetch-aawsat-com-every-33-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aawsat_com',
        'schedule': crontab(minute='*/33'),
    },
    
    'fetch-alkhaleejonline-net-every-25-minutes': {
        'task': 'scraper.tasks.fetch_news_links_alkhaleejonline_net',
        'schedule': crontab(minute='*/25'),
    },

    # 'fetch-arabi21-com-every-8-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_arabi21_com',
    #     'schedule': crontab(minute='*/8'),
    # },

    'fetch-arab48-com-every-15-minutes': {
        'task': 'scraper.tasks.fetch_news_links_arab48_com',
        'schedule': crontab(minute='*/15'),
    },

    'fetch-oka-com-sa-every-12-minutes': {
        'task': 'scraper.tasks.fetch_news_links_okaz_com_sa',
        'schedule': crontab(minute='*/12'),
    },

    # 'fetch-spa-gov-sa-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_spa_gov_sa',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-qna-org-qa-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_qna_org_qa',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-wam-ae-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_wam_ae',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-omannews-gov-om-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_omannews_gov_om',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-kuna-net-kw-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_kuna_net_kw',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-bna-bh-every-43-minutes': {
        'task': 'scraper.tasks.fetch_news_links_bna_bh',
        'schedule': crontab(minute='*/43'),
    },
    
    # 'fetch-nna-leb-gov-lb-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_nna_leb_gov_lb',
    #     'schedule': crontab(minute='*'),
    # },

    # 'fetch-sana-sy-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_sana_sy',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-alsumaria-tv-every-28-minutes': {
        'task': 'scraper.tasks.fetch_news_links_alsumaria_tv',
        'schedule': crontab(minute='*/28'),
    },
    
    'fetch-alittihad-tv-every-27-minutes': {
        'task': 'scraper.tasks.fetch_news_links_alittihad_tv',
        'schedule': crontab(minute='*/27'),
    },
    
    # 'fetch-syriahr-com-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_syriahr_com',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-southfront-press-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_southfront_press',
    #     'schedule': crontab(minute='*'),
    # },
    
    # 'fetch-ina-iq-every-minute': {
    #     'task': 'scraper.tasks.fetch_news_links_ina_iq',
    #     'schedule': crontab(minute='*'),
    # },

    'fetch-dc-fes-de-every-16-minutes': {
        'task': 'scraper.tasks.fetch_news_links_dc_fes_de',
        'schedule': crontab(minute='*/16'),
    },
    
    'fetch-freiheit-org-every-17-minutes': {
        'task': 'scraper.tasks.fetch_news_links_freiheit_org',
        'schedule': crontab(minute='*/17'),
    },
    
    'fetch-boell-de-every-18-minutes': {
        'task': 'scraper.tasks.fetch_news_links_boell_de',
        'schedule': crontab(minute='*/18'),
    },
    
    'fetch-hss-de-every-19-minutes': {
        'task': 'scraper.tasks.fetch_news_links_hss_de',
        'schedule': crontab(minute='*/19'),
    },

    'fetch-spiegel-de-every-24-minutes': {
        'task': 'scraper.tasks.fetch_news_links_spiegel_de',
        'schedule': crontab(minute='*/24'),
    },
    
    'fetch-bild-de-every-8-minutes': {
        'task': 'scraper.tasks.fetch_news_links_bild_de',
        'schedule': crontab(minute='*/8'),
    },
    
    'fetch-zdfheute-de-every-9-minutes': {
        'task': 'scraper.tasks.fetch_news_links_zdfheute_de',
        'schedule': crontab(minute='*/9'),
    },
    
    'fetch-rsf-org-every-6-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rsf_org',
        'schedule': crontab(minute='*/6'),
    },
    
    'fetch-almanar-com-lb-every-21-minutes': {
        'task': 'scraper.tasks.fetch_news_links_almanar_com_lb',
        'schedule': crontab(minute='*/21'),
    },

    # 'fetch-iswnews-com-ye-every-65-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_iswnews_com',
    #     'schedule': crontab(minute='*/65'),
    # },
    
    'fetch-longwarjournal-org-every-20-minutes': {
        'task': 'scraper.tasks.fetch_news_links_longwarjournal_org',
        'schedule': crontab(minute='*/20'),
    },

    'fetch-pakobserver-net-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_pakobserver_net',
        'schedule': crontab(minute='*/23'),
    },
    
    'fetch-afghanistan-ru-every-21-minutes': {
        'task': 'scraper.tasks.fetch_news_links_afghanistan_ru',
        'schedule': crontab(minute='*/21'),
    },

    'fetch-voanews-com-every-22-minutes': {
        'task': 'scraper.tasks.fetch_news_links_voanews_com',
        'schedule': crontab(minute='*/22'),
    },
    
    'fetch-makorrishon-co-il-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_makorrishon_co_il',
        'schedule': crontab(minute='*/23'),
    },
    
    'fetch-vesti-ru-every-11-minutes': {
        'task': 'scraper.tasks.fetch_news_links_vesti_ru',
        'schedule': crontab(minute='*/11'),
    },
    
    'fetch-kp-ru-every-12-minutes': {
        'task': 'scraper.tasks.fetch_news_links_kp_ru',
        'schedule': crontab(minute='*/12'),
    },

    'fetch-mikroskopmedia-com-every-24-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mikroskopmedia_com',
        'schedule': crontab(minute='*/24'),
    },
    
    # 'fetch-amnesty-org-every-54-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_amnesty_org',
    #     'schedule': crontab(minute='*/54'),
    # },
    
    'fetch-rambler-ru-every-13-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rambler_ru',
        'schedule': crontab(minute='*/13'),
    },

    'fetch-gazeta-ru-every-14-minutes': {
        'task': 'scraper.tasks.fetch_news_links_gazeta_ru',
        'schedule': crontab(minute='*/14'),
    },
    
    'fetch-rg-ru-every-7-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rg_ru',
        'schedule': crontab(minute='*/7'),
    },
    
    'fetch-aif-ru-every-25-minutes': {
        'task': 'scraper.tasks.fetch_news_links_aif_ru',
        'schedule': crontab(minute='*/25'),
    },
    
    'fetch-interfax-ru-every-26-minutes': {
        'task': 'scraper.tasks.fetch_news_links_interfax_ru',
        'schedule': crontab(minute='*/26'),
    },
    
    'fetch-ntv-ru-every-31-minutes': {
        'task': 'scraper.tasks.fetch_news_links_ntv_ru',
        'schedule': crontab(minute='*/31'),
    },
    
    'fetch-news-mail-ru-every-29-minutes': {
        'task': 'scraper.tasks.fetch_news_links_news_mail_ru',
        'schedule': crontab(minute='*/29'),
    },
    
    'fetch-rediff-com-every-33-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rediff_com',
        'schedule': crontab(minute='*/33'),
    },
    
    # 'fetch-moneycontrol-com-every-13-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_moneycontrol_com',
    #     'schedule': crontab(minute='*/13'),
    # },

    'fetch-economictimes-indiatimes-com-every-14-minutes': {
        'task': 'scraper.tasks.fetch_news_links_economictimes_indiatimes_com',
        'schedule': crontab(minute='*/14'),
    },
    
    'fetch-news-onmanorama-com-every-53-minutes': {
        'task': 'scraper.tasks.fetch_news_links_onmanorama_com',
        'schedule': crontab(minute='*/53'),
    },
    
    'fetch-news-mathrubhumi-com-every-31-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mathrubhumi_com',
        'schedule': crontab(minute='*/31'),
    },
    
    'fetch-dw-com-en-every-23-minutes': {
        'task': 'scraper.tasks.fetch_news_links_dw_com_en',
        'schedule': crontab(minute='*/23'),
    },
    
    'fetch-ir-voanews-com-en-every-32-minutes': {
        'task': 'scraper.tasks.fetch_news_links_ir_voanews_com',
        'schedule': crontab(minute='*/32'),
    },
    
    # 'fetch-asriran-com-every-10-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_asriran_com',
    #     'schedule': crontab(minute='*/10'),
    # },
    
    # 'fetch-rajanews-com-every-23-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_rajanews_com',
    #     'schedule': crontab(minute='*/23'),
    # },
    
    # 'fetch-jahannews-com-every-27-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_jahannews_com',
    #     'schedule': crontab(minute='*/27'),
    # },
    
    # 'fetch-beytoote-com-every-71-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_beytoote_com',
    #     'schedule': crontab(minute='*/71'),
    # },
    
    'fetch-tehrantimes-com-every-17-minutes': {
        'task': 'scraper.tasks.fetch_news_links_tehrantimes_com',
        'schedule': crontab(minute='*/17'),
    },

    # 'fetch-sharghdaily-com-every-373-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_sharghdaily_com',
    #     'schedule': crontab(minute='*/373'),
    # },
    
    'fetch-nournews-ir-every-19-minutes': {
        'task': 'scraper.tasks.fetch_news_links_nournews_ir',
        'schedule': crontab(minute='*/19'),
    },
    
    # 'fetch-mizanonline-ir-every-17-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_mizanonline_ir',
    #     'schedule': crontab(minute='*/17'),
    # },
    
    # 'fetch-inn-ir-every-21-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_inn_ir',
    #     'schedule': crontab(minute='*/21'),
    # },
    
    'fetch-irannewsupdate-com-every-33-minutes': {
        'task': 'scraper.tasks.fetch_news_links_irannewsupdate_com',
        'schedule': crontab(minute='*/33'),
    },
    
    # 'fetch-ettelaat-com-every-12-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_ettelaat_com',
    #     'schedule': crontab(minute='*/12'),
    # },
    
    'fetch-bahardaily-ir-every-7-minutes': {
        'task': 'scraper.tasks.fetch_news_links_bahardaily_ir',
        'schedule': crontab(minute='*/7'),
    },
    
    # 'fetch-resalat-news-com-every-19-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_resalat_news_com',
    #     'schedule': crontab(minute='*/19'),
    # },
    
    # 'fetch-icana-ir-every-17-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_icana_ir',
    #     'schedule': crontab(minute='*/17'),
    # },
    
    # 'fetch-siasatrooz-ir-every-18-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_siasatrooz_ir',
    #     'schedule': crontab(minute='*/18'),
    # },
    
    # 'fetch-mardomsalari-ir-every-19-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_mardomsalari_ir',
    #     'schedule': crontab(minute='*/19'),
    # },
    
    # 'fetch-vatanemrooz-ir-every-23-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_vatanemrooz_ir',
    #     'schedule': crontab(minute='*/23'),
    # },
    
    # 'fetch-esfahanemrooz-ir-every-25-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_esfahanemrooz_ir',
    #     'schedule': crontab(minute='*/25'),
    # },
    
    'fetch-iran-emrooz-net-every-37-minutes': {
        'task': 'scraper.tasks.fetch_news_links_iran_emrooz_net',
        'schedule': crontab(minute='*/37'),
    },
    
    # 'fetch-jahanesanat-ir-every-21-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_jahanesanat_ir',
    #     'schedule': crontab(minute='*/21'),
    # },
    
    # 'fetch-eghtesademeli-com-every-24-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_eghtesademeli_com',
    #     'schedule': crontab(minute='*/24'),
    # },
    
    # 'fetch-eghtesadepooya-ir-every-21-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_eghtesadepooya_ir',
    #     'schedule': crontab(minute='*/21'),
    # },
    
    # 'fetch-toseeirani-ir-every-17-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_toseeirani_ir',
    #     'schedule': crontab(minute='*/17'),
    # },
    
    # 'fetch-sayeh-news-com-every-25-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_sayeh_news_com',
    #     'schedule': crontab(minute='*/25'),
    # },
    
    # 'fetch-hamdelidaily-ir-every-13-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_hamdelidaily_ir',
    #     'schedule': crontab(minute='*/13'),
    # },
    
    'fetch-iranpressnews-com-every-26-minutes': {
        'task': 'scraper.tasks.fetch_news_links_iranpressnews_com',
        'schedule': crontab(minute='*/26'),
    },
    
    'fetch-theiranpost-com-every-27-minutes': {
        'task': 'scraper.tasks.fetch_news_links_theiranpost_com',
        'schedule': crontab(minute='*/27'),
    },
    
    'fetch-dailysabah-com-every-18-minutes': {
        'task': 'scraper.tasks.fetch_news_links_dailysabah_com',
        'schedule': crontab(minute='*/18'),
    },
    
    'fetch-wanaen-com-every-28-minutes': {
        'task': 'scraper.tasks.fetch_news_links_wanaen_com',
        'schedule': crontab(minute='*/28'),
    },
    
    'fetch-mek-iran-com-every-29-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mek_iran_com',
        'schedule': crontab(minute='*/29'),
    },
    
    'fetch-mojahedin-org-every-30-minutes': {
        'task': 'scraper.tasks.fetch_news_links_mojahedin_org',
        'schedule': crontab(minute='*/30'),
    },
    
    # 'fetch-nejatngo-org-every-251-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_nejatngo_org',
    #     'schedule': crontab(minute='*/251'),
    # },
    
    # 'fetch-imna-ir-every-49-minutes': {
    #     'task': 'scraper.tasks.fetch_news_links_imna_ir',
    #     'schedule': crontab(minute='*/49'),
    # },
    
    'fetch-iranfocus-com-every-52-minutes': {
        'task': 'scraper.tasks.fetch_news_links_iranfocus_com',
        'schedule': crontab(minute='*/52'),
    },
    
    'fetch-themoscowtimes-com-every-33-minutes': {
        'task': 'scraper.tasks.fetch_news_links_themoscowtimes_com',
        'schedule': crontab(minute='*/33'),
    },
    
    'fetch-meduza-io-every-31-minutes': {
        'task': 'scraper.tasks.fetch_news_links_meduza_io',
        'schedule': crontab(minute='*/31'),
    },
    
    'fetch-rt-com-every-7-minutes': {
        'task': 'scraper.tasks.fetch_news_links_rt_com',
        'schedule': crontab(minute='*/7'),
    },
    
    'fetch-kyivpost-com-every-13-minutes': {
        'task': 'scraper.tasks.fetch_news_links_kyivpost_com',
        'schedule': crontab(minute='*/13'),
    },

    #------------------TELEGRAM------------------
    
    'scrape-bbc-every-47-minutes': {
        'task': 'scraper.tasks.scrape_bbc_channel',
        'schedule': crontab(minute='*/47'), 
    },
    
    'scrape-oxuaze-every-48-minutes': {
        'task': 'scraper.tasks.scrape_oxuaze_channel',
        'schedule': crontab(minute='*/48'),  
    },
    
    'scrape-reartsakh-every-49-minutes': {
        'task': 'scraper.tasks.scrape_reartsakh_channel',
        'schedule': crontab(minute='*/49'),  
    },

    'scrape-bagramyan26-every-50-minutes': {
        'task': 'scraper.tasks.scrape_bagramyan26_channel',
        'schedule': crontab(minute='*/50'),  
    },
    
    'scrape-economy-of-armenia-every-51-minutes': {
        'task': 'scraper.tasks.scrape_economy_of_armenia_channel',
        'schedule': crontab(minute='*/51'),  
    },

    'scrape-miacun-every-52-minutes': {
        'task': 'scraper.tasks.scrape_miacum_channel',
        'schedule': crontab(minute='*/52'),  
    },
    
    'scrape-sismasis-every-53-minutes': {
        'task': 'scraper.tasks.scrape_sismasis_channel',
        'schedule': crontab(minute='*/53'),  
    },
    
    'scrape-karabakh-records-every-54-minutes': {
        'task': 'scraper.tasks.scrape_karabakh_records_channel',
        'schedule': crontab(minute='*/54'),  
    },
    
    'scrape-russkaya-obsina-zov-every-55-minutes': {
        'task': 'scraper.tasks.scrape_russkaya_obsina_zov_channel',
        'schedule': crontab(minute='*/55'),  
    },


    'scrape-meydan-tv-every-57-minutes': {
        'task': 'scraper.tasks.scrape_meydan_tv_channel',
        'schedule': crontab(minute='*/57'),  
    },

    'scrape-azadliq-radiosu-every-58-minutes': {
        'task': 'scraper.tasks.scrape_azadliq_radiosu_channel',
        'schedule': crontab(minute='*/58'),  
    },

    'scrape-eco-expert-every-59-minutes': {
        'task': 'scraper.tasks.scrape_eco_expert_channel',
        'schedule': crontab(minute='*/59'),  
    },

    'scrape-qafqaz-info-every-60-minutes': {
        'task': 'scraper.tasks.scrape_qafqaz_info_channel',
        'schedule': crontab(minute='*/60'),
    },

    'scrape-modern-azz-every-61-minutes': {
        'task': 'scraper.tasks.scrape_modern_azz_channel',
        'schedule': crontab(minute='*/61'),  
    },

    'scrape-baku-es-every-62-minutes': {
        'task': 'scraper.tasks.scrape_baku_es_channel',
        'schedule': crontab(minute='*/62'),  
    },

    'scrape-shedevr-plus-every-63-minutes': {
        'task': 'scraper.tasks.scrape_shedevr_plus_channel',
        'schedule': crontab(minute='*/63'),
    },

    'scrape-isayevios-every-64-minutes': {
        'task': 'scraper.tasks.scrape_isayevios_channel',
        'schedule': crontab(minute='*/64'),  
    },

    'scrape-azxeber1-every-65-minutes': {
        'task': 'scraper.tasks.scrape_azxeber1_channel',
        'schedule': crontab(minute='*/65'),
    },

    'scrape-maraqli-tv-every-66-minutes': {
        'task': 'scraper.tasks.scrape_maraqli_tv_channel',
        'schedule': crontab(minute='*/66'),  
    },

    'scrape-bakutvxeber-every-67-minutes': {
        'task': 'scraper.tasks.scrape_bakutvxeber_channel',
        'schedule': crontab(minute='*/67'),
    },

    'scrape-Axaraz-every-68-minutes': {
        'task': 'scraper.tasks.scrape_Axaraz_channel',
        'schedule': crontab(minute='*/68'),  
    },

    'scrape-tvictimai-every-69-minutes': {
        'task': 'scraper.tasks.scrape_tvictimai_channel',
        'schedule': crontab(minute='*/69'),
    },

    'scrape-operativmedia-every-70-minutes': {
        'task': 'scraper.tasks.scrape_operativmedia_channel',
        'schedule': crontab(minute='*/70'),  
    },

    'scrape-sonxeberler-every-71-minutes': {
        'task': 'scraper.tasks.scrape_sonxeberler_channel',
        'schedule': crontab(minute='*/71'),  
    },

    'scrape-P_apirus-every-72-minutes': {
        'task': 'scraper.tasks.scrape_P_apirus_channel',
        'schedule': crontab(minute='*/72'),  
    },

    'scrape-trthaberdijital-every-73-minutes': {
        'task': 'scraper.tasks.scrape_trthaberdijital_channel',
        'schedule': crontab(minute='*/73'),  
    },

    'scrape-gundemedairhs-every-74-minutes': {
        'task': 'scraper.tasks.scrape_gundemedairhs_channel',
        'schedule': crontab(minute='*/74'),  
    },

    'scrape-bpthaber-every-55-minutes': {
        'task': 'scraper.tasks.scrape_bpthaber_channel',
        'schedule': crontab(minute='*/55'),  
    },

    'scrape-konseyhaber-every-56-minutes': {
        'task': 'scraper.tasks.scrape_konseyhaber_channel',
        'schedule': crontab(minute='*/56'),  
    },

    'scrape-turkiyedenhaberler24-every-57-minutes': {
        'task': 'scraper.tasks.scrape_turkiyedenhaberler24_channel',
        'schedule': crontab(minute='*/57'),  
    },

    'scrape-PulseGundem-every-58-minutes': {
        'task': 'scraper.tasks.scrape_PulseGundem_channel',
        'schedule': crontab(minute='*/58'),  
    },

    'scrape-ataturkcumedyaorg-every-59-minutes': {
        'task': 'scraper.tasks.scrape_ataturkcumedyaorg_channel',
        'schedule': crontab(minute='*/59'),  
    },
    
    'scrape-rian_ru-every-60-minutes': {
        'task': 'scraper.tasks.scrape_rian_ru_channel',
        'schedule': crontab(minute='*/60'),  
    },

    'scrape-nwsru-every-61-minutes': {
        'task': 'scraper.tasks.scrape_nwsru_channel',
        'schedule': crontab(minute='*/61'),  
    },

    'scrape-anna_news-every-62-minutes': {
        'task': 'scraper.tasks.scrape_anna_news_channel',
        'schedule': crontab(minute='*/62'),  
    },

    'scrape-bbcrussian-every-63-minutes': {
        'task': 'scraper.tasks.scrape_bbcrussian_channel',
        'schedule': crontab(minute='*/63'),  
    },

    'scrape-lentadnya-every-64-minutes': {
        'task': 'scraper.tasks.scrape_lentadnya_channel',
        'schedule': crontab(minute='*/64'),  
    },

    'scrape-uniannet-every-65-minutes': {
        'task': 'scraper.tasks.scrape_uniannet_channel',
        'schedule': crontab(minute='*/65'),  
    },

    'scrape-breakingmash-every-66-minutes': {
        'task': 'scraper.tasks.scrape_breakingmash_channel',
        'schedule': crontab(minute='*/66'),  
    },

    'scrape-bbbreaking-every-67-minutes': {
        'task': 'scraper.tasks.scrape_bbbreaking_channel',
        'schedule': crontab(minute='*/67'),  
    },

    'scrape-moscowach-every-68-minutes': {
        'task': 'scraper.tasks.scrape_moscowach_channel',
        'schedule': crontab(minute='*/68'),  
    },

    'scrape-bazabazon-every-69-minutes': {
        'task': 'scraper.tasks.scrape_bazabazon_channel',
        'schedule': crontab(minute='*/69'),  
    },

    'scrape-readovkanews-every-70-minutes': {
        'task': 'scraper.tasks.scrape_readovkanews_channel',
        'schedule': crontab(minute='*/70'),  
    },

    'scrape-rt_russian-every-71-minutes': {
        'task': 'scraper.tasks.scrape_rt_russian_channel',
        'schedule': crontab(minute='*/71'),  
    },

    'scrape-rbc_news-every-72-minutes': {
        'task': 'scraper.tasks.scrape_rbc_news_channel',
        'schedule': crontab(minute='*/72'),  
    },

    'scrape-tass_agency-every-73-minutes': {
        'task': 'scraper.tasks.scrape_tass_agency_channel',
        'schedule': crontab(minute='*/73'),  
    },

    'scrape-infomoscow24-every-74-minutes': {
        'task': 'scraper.tasks.scrape_infomoscow24_channel',
        'schedule': crontab(minute='*/74'),  
    },

    'scrape-tvrain-every-75-minutes': {
        'task': 'scraper.tasks.scrape_tvrain_channel',
        'schedule': crontab(minute='*/75'),  
    },

    'scrape-e1_news-every-76-minutes': {
        'task': 'scraper.tasks.scrape_e1_news_channel',
        'schedule': crontab(minute='*/76'),  
    },
    
    # "process-notifications-telegram-every-5-minutes": {
    #     "task": "scraper.tasks.celery_process_notifications_telegram", 
    #     "schedule": crontab(minute="*"),
    # },

    'create-article-problems-every-5-minutes': {
        'task': 'scraper.tasks.celery_check_fields',
        'schedule': crontab(minute='*/5'),
    },
    
    #     'send-telegram-notification': {
    #     'task': 'scraper.tasks.celery_notify',
    #     'schedule': crontab(minute='*'),  
    # }

}

# CELERY_BEAT_SCHEDULE = {
#     "send-email-morning": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=9, minute=0),
#         "options": {"queue": "email_queue"},
#     },
#     "send-email-noon": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=14, minute=45),
#         "options": {"queue": "email_queue"},
#     },
#     "send-email-evening": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=14, minute=47),
#         "options": {"queue": "email_queue"},
#     },
#     "send-email-night": {
#         "task": "scraper.tasks.celery_send_keywords_emails",
#         "schedule": crontab(hour=14, minute=49),
#         "options": {"queue": "email_queue"},
#     },

#     "celery-build-temp-mail-data": {
#         "task": "scraper.tasks.celery_build_temp_mail_data",
#         "schedule": crontab(minute="*/2"),
#         "options": {"queue": "email_queue"},
#     },


#     'fetch-uz-sputniknews-ru-every-23-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_uz_sputniknews_ru',
#         'schedule': crontab(minute='*/2'), 
#         'options': {'queue': 'default'},
#     },
    
#     'fetch-ulusal-every-19-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_ulusal',
#         'schedule': crontab(minute='*/3'), 
#     },
    
#     'fetch-gazeta-uz-every-25-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_gazeta_uz',
#         'schedule': crontab(minute='*/4'), 
#     },

#     'fetch-haberler-every-3-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_haberler',
#         'schedule': crontab(minute='*/5'),
#     },

#     'fetch-am-sputniknews-ru-every-16-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_am_sputniknews_ru',
#         'schedule': crontab(minute='*/6'), 
#     },

#     'fetch-izru-every-3-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_izru',
#         'schedule': crontab(minute='*/3'),
#     },

#     'fetch-lentaru-every-4-minutes': {
#         'task': 'scraper.tasks.fetch_news_links_lentaru',
#         'schedule': crontab(minute='*/4'),
#     },
# }

CELERY_TASK_QUEUES = {  
    'email_queue': {  
        'exchange': 'email_queue',  
        'routing_key': 'email_queue',  
    },  
    'scrape_queue': {  
        'exchange': 'scrape_queue',  
        'routing_key': 'scrape_queue',  
    },  
}
CELERY_TASK_DEFAULT_QUEUE = 'scrape_queue'


#CELERY_RESULT_BACKEND = 'django-db'

TELEGRAM_API_ID=13082905
TELEGRAM_API_HASH="08dd43a26927d34884c99ef456677a23"
# TELEGRAM_BOT_TOKEN="7444532118:AAG9xCkQzID20X99Aip9KHuRMtotMxnR6w4"    

TELEGRAM_BOT_TOKEN = "8391838035:AAE1o_53xV6Kj-_NRKPo2xb2T4iy162QwY4"

TIME_ZONE = 'Asia/Baku'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'visiontechazsolutions@gmail.com'
EMAIL_HOST_PASSWORD = 'sxbe ewco dfet etaq'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#_----------------SANIYE UCUN NUMUNELER-----------------


# 'task_2': {
#     'task': 'scraper.tasks.task_2',
#     'schedule': crontab(minute='*', second=30),  # Her deqiqenin 30. saniyesinde
# },
