# Generated by Django 5.1 on 2025-05-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True, verbose_name='Açar sözlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Açar sözlər',
                'verbose_name_plural': 'Açar sözlər',
            },
        ),
        migrations.CreateModel(
            name='KeyNewsArticleCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsarticle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_combinations', to='scraper.newsarticle', verbose_name='Məqalələrinin id-si')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_combinations', to='tasks.keywords', verbose_name='Açar sözlərin id-si')),
            ],
            options={
                'verbose_name': 'Açar sözə uyğun məqalə id-si',
                'verbose_name_plural': 'Açar sözlərə uyğun məqalə id-ləri',
            },
        ),
        migrations.CreateModel(
            name='KeywordsUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User id-si')),
                ('email_notification', models.BooleanField(default=False, verbose_name='Email gonderilmelidirmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='tasks.keywords', verbose_name='Açar sözlərin id-si')),
            ],
            options={
                'verbose_name': 'Açar sözə uyğun user id-si',
                'verbose_name_plural': 'Açar sözlərə uyğun user id-ləri',
            },
        ),
    ]
