# Generated by Django 5.1 on 2025-11-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_alter_changednewsarticle_title_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='keywordsuserrelation',
            options={'verbose_name': 'Keyword User Relation', 'verbose_name_plural': 'Keyword User Relations'},
        ),
        migrations.AddField(
            model_name='keywordsuserrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=200, unique=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='keywordsuserrelation',
            name='email_notification',
            field=models.BooleanField(default=False, verbose_name='Email Notification'),
        ),
        migrations.AlterField(
            model_name='keywordsuserrelation',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keywords', to='tasks.keywords', verbose_name='Keywords id'),
        ),
        migrations.AlterField(
            model_name='keywordsuserrelation',
            name='user_id',
            field=models.IntegerField(verbose_name='User id'),
        ),
        migrations.CreateModel(
            name='KeywordsNewsArticleCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_articles', to='tasks.keywords', verbose_name='Keywords id')),
                ('newsarticle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsarticle_keywords', to='scraper.newsarticle', verbose_name='NewsArticle id')),
            ],
            options={
                'verbose_name': 'Keyword NewsArticle Combination',
                'verbose_name_plural': 'Keyword NewsArticle Combinations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('status', models.BooleanField(default=False, verbose_name='Notification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_keywords', to='tasks.keywords', verbose_name='Keywords id')),
                ('newsarticle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_articles', to='scraper.newsarticle', verbose_name='NewsArticle id')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.DeleteModel(
            name='KeyNewsArticleCombination',
        ),
    ]
