# Generated by Django 5.1 on 2026-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_keywords_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsuserrelation',
            name='telegram_notification',
            field=models.BooleanField(default=False, verbose_name='Telegram Notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='telegram_status',
            field=models.BooleanField(default=False, verbose_name='Telegram status'),
        ),
    ]
