# Generated by Django 5.1 on 2026-03-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_keywordsuserrelation_telegram_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='User id')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Username')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Chat id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='keywordsnewsarticlecombination',
            name='keyword_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Keywords id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='keyword_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Keywords id'),
        ),
        migrations.RemoveField(
            model_name='keywordsuserrelation',
            name='keyword_id',
        ),
        migrations.AlterField(
            model_name='keywordsnewsarticlecombination',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User id'),
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='KeywordsUserRelation',
        ),
    ]
