# Generated by Django 5.1 on 2026-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_telegramuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_status',
            field=models.BooleanField(default=False, verbose_name='Email status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='has_sent_email',
            field=models.BooleanField(default=False, verbose_name='Has sent email'),
        ),
        migrations.AddField(
            model_name='notification',
            name='has_sent_telegram',
            field=models.BooleanField(default=False, verbose_name='Has sent telegram'),
        ),
    ]
