# Generated by Django 5.1 on 2026-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_alter_changednewsarticle_title_and_more'),
        ('tasks', '0005_remove_notification_status_notification_email_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_status', 'has_sent_email', 'user_id'], name='tasks_notif_email_s_24ed87_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id'], name='tasks_notif_user_id_23b12d_idx'),
        ),
    ]
