# Generated by Django 5.1 on 2026-03-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_alter_changednewsarticle_title_and_more'),
        ('tasks', '0006_notification_tasks_notif_email_s_24ed87_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keywordsnewsarticlecombination',
            index=models.Index(fields=['user_id'], name='tasks_keywo_user_id_ba2db7_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordsnewsarticlecombination',
            index=models.Index(fields=['newsarticle_id'], name='tasks_keywo_newsart_d96cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordsnewsarticlecombination',
            index=models.Index(fields=['keyword_id'], name='tasks_keywo_keyword_70b1ea_idx'),
        ),
    ]
