# Generated by Django 5.1 on 2026-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_alter_changednewsarticle_title_and_more'),
        ('tasks', '0007_keywordsnewsarticlecombination_tasks_keywo_user_id_ba2db7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='tasks_notif_email_s_24ed87_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='tasks_notif_user_id_23b12d_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_status', 'has_sent_email'], name='tasks_notif_email_s_d99ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id', 'email_status', 'has_sent_email'], name='tasks_notif_user_id_b4f275_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='tasks_notif_created_02b083_idx'),
        ),
    ]
