# Generated by Django 5.1 on 2026-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_exclude_unique_exclude_per_source'),
        ('tasks', '0008_remove_notification_tasks_notif_email_s_24ed87_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDataEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User id')),
                ('match_keyword_newsarticle', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('newsarticles', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Temp mail data',
                'verbose_name_plural': 'Temp mail data',
            },
        ),
        migrations.CreateModel(
            name='TempDataTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User id')),
                ('match_keyword_newsarticle', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('newsarticles', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Temp telegram data',
                'verbose_name_plural': 'Temp telegram data',
            },
        ),
        migrations.AddField(
            model_name='keywordsnewsarticlecombination',
            name='email_status',
            field=models.BooleanField(default=False, verbose_name='Email status'),
        ),
        migrations.AddField(
            model_name='keywordsnewsarticlecombination',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keywordsnewsarticlecombination',
            name='telegram_status',
            field=models.BooleanField(default=False, verbose_name='Telegram status'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordsnewsarticlecombination',
            unique_together={('user_id', 'keyword_id', 'newsarticle_id')},
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
