# Generated by Django 5.1 on 2026-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tempdataemail_tempdatatelegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdataemail',
            name='newsarticles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
