# Generated by Django 5.1 on 2026-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tempdataemail_newsarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdataemail',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempdataemail',
            name='match_keyword_newsarticle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
