# Generated by Django 5.1 on 2026-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tempdataemail_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordsnewsarticlecombination',
            old_name='is_processed',
            new_name='is_email_processed',
        ),
        migrations.AddField(
            model_name='keywordsnewsarticlecombination',
            name='is_telegram_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tempdatatelegram',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempdatatelegram',
            name='match_keyword_newsarticle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempdatatelegram',
            name='newsarticles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
